import { setNutrients } from './set-nutrients.js';

const micronutrientsArr = [
  {
    name: "VitaminA RAE",
    key: "vit_a_rae",
    value: 0,
    unitOfMeasurement: "µg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin A",
    key: "vit_a",
    value: 0,
    unitOfMeasurement: "IU",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin C",
    key: "vit_c",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin D",
    key: "vit_d",
    value: 0,
    unitOfMeasurement: "µg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin E",
    key: "vit_e",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin K",
    key: "vit_k",
    value: 0,
    unitOfMeasurement: "µg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin B1",
    key: "vit_b1",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin B2",
    key: "vit_b2",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin B3",
    key: "vit_b3",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin B5",
    key: "vit_b5",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin B6",
    key: "vit_b6",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin B9",
    key: "vit_b9",
    value: 0,
    unitOfMeasurement: "µg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Vitamin B12",
    key: "vit_b12",
    value: 0,
    unitOfMeasurement: "µg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Choline",
    key: "choline",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Copper",
    key: "copper",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Fluoride",
    key: "fluoride",
    value: 0,
    unitOfMeasurement: "µg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Iron",
    key: "iron",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Magnesium",
    key: "magnesium",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Manganese",
    key: "manganese",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Phosphoru",
    key: "phosphoru",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Potassium",
    key: "potassium",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Selenium",
    key: "selenium",
    value: 0,
    unitOfMeasurement: "µg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Sodium",
    key: "sodium",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
  {
    name: "Zinc",
    key: "zinc",
    value: 0,
    unitOfMeasurement: "mg",
    percentageOfTotal: 0,
    dailyLimit: 0,
  },
];

export function setMicronutrients(food, micronutrients) {
  return setNutrients(food, micronutrients, micronutrientsArr);
}
