name: Deploy Node Application

on: 
  push:
    branches:  # ✅ Typo fixed here (was: "brances")
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t sava995/fitquol .

      - name: Publish image to Docker Hub
        run: docker push sava995/fitquol:latest

  deploy: 
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pull image from Docker Hub
        run: docker pull sava995/fitquol:latest

      - name: Delete old container
        run: docker rm -f nodejs-app-container

      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name nodejs-app-container sava995/fitquol:latest
