const mongoose = require("mongoose");

const foodSchema = mongoose.Schema(
  {
    food: { type: String, required: true },
    calories: { type: Number, required: true },
    carbohydrates: { type: Number },
    net_carbs: { type: Number },
    fiber: { type: Number },
    fats: { type: Number },
    saturated: { type: Number },
    mufa: { type: Number },
    pufa: { type: Number },
    pufa_w6: { type: Number },
    pufa_w3: { type: Number },
    protein: { type: Number },
    vit_a_rae: { type: Number },
    vit_a: { type: Number },
    vit_b1: { type: Number },
    vit_b2: { type: Number },
    vit_b3: { type: Number },
    vit_b5: { type: Number },
    vit_b6: { type: Number },
    vit_b9: { type: Number },
    vit_b12: { type: Number },
    vit_c: { type: Number },
    vit_d: { type: Number },
    vit_e: { type: Number },
    vit_k: { type: Number },
    choline: { type: Number },
    betaine: { type: Number },
    calcium: { type: Number },
    copper: { type: Number },
    fluoride: { type: Number },
    iron: { type: Number },
    magnesium: { type: Number },
    manganese: { type: Number },
    phosphorus: { type: Number },
    potassium: { type: Number },
    selenium: { type: Number },
    sodium: { type: Number },
    zinc: { type: Number },
    other_names: { type: String },
    comments: { type: String },
    source: { type: String },
    category: { type: String },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Food", foodSchema);
